#include "config/backends.hpp"

#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cerrno>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include <nlohmann/json.hpp>

#include "ipc/paths.hpp"

namespace choir {

namespace fs = std::filesystem;

namespace {

// The two injected backends, named identically in the AppImage payload and in
// ~/.local/lib/choir (and matching what meson installs for source/pacman builds).
constexpr const char* kLayerLib = "libchoir_overlay.so";
constexpr const char* kGlLib = "libchoir_gl.so";

std::string env_or(const char* name, const std::string& fallback) {
    const char* v = std::getenv(name);
    if (v && v[0] != '\0') return std::string(v);
    return fallback;
}

bool read_file(const fs::path& path, std::string& out) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return false;
    std::ostringstream ss;
    ss << in.rdbuf();
    if (in.bad()) return false;
    out = ss.str();
    return true;
}

// Write `bytes` to `path` with mode `mode` via a sibling temp file + rename.
//
// The rename is load-bearing, not tidiness: truncating a .so in place while a game
// still has it mapped fails with ETXTBSY, so an update launched with a game running
// would leave the overlay half-installed. Renaming swaps the directory entry and
// leaves the running process on its old inode. It also means a torn write can never
// be observed as a plausible-looking manifest.
bool write_atomic(const fs::path& path, const std::string& bytes, mode_t mode) {
    std::error_code ec;
    fs::create_directories(path.parent_path(), ec);
    if (ec) return false;

    const fs::path tmp = path.string() + ".choir-tmp";
    const int fd = ::open(tmp.c_str(), O_CREAT | O_WRONLY | O_TRUNC, mode);
    if (fd < 0) return false;
    // O_CREAT's mode is masked by umask, and ignored outright if tmp pre-existed.
    ::fchmod(fd, mode);

    const char* p = bytes.data();
    size_t left = bytes.size();
    bool ok = true;
    while (left > 0) {
        const ssize_t n = ::write(fd, p, left);
        if (n < 0) {
            if (errno == EINTR) continue;
            ok = false;
            break;
        }
        p += n;
        left -= static_cast<size_t>(n);
    }
    if (::close(fd) != 0) ok = false;
    if (ok && ::rename(tmp.c_str(), path.c_str()) != 0) ok = false;
    if (!ok) fs::remove(tmp, ec);
    return ok;
}

// POSIX single-quote escaping, for interpolating a path into the generated shell
// wrapper. $HOME is user-controlled and ends up on a line that launches their games.
std::string shell_quote(const std::string& s) {
    std::string out = "'";
    for (char c : s) {
        if (c == '\'') {
            out += "'\\''";  // close, escaped quote, reopen
        } else {
            out += c;
        }
    }
    out += "'";
    return out;
}

// Kept in sync by hand with src/layer/manifest/choir_overlay.json.in, which meson
// templates for source/pacman installs. Built through nlohmann rather than
// concatenated so a $HOME containing a quote or backslash cannot produce a manifest
// that fails to parse — which would take the overlay down in every Vulkan game.
std::string layer_manifest(const std::string& lib_path) {
    nlohmann::json j;
    j["file_format_version"] = "1.2.0";
    j["layer"] = {
        {"name", "VK_LAYER_choir_overlay_x86_64"},
        {"type", "GLOBAL"},
        {"library_path", lib_path},
        {"api_version", "1.1.0"},
        {"implementation_version", "1"},
        {"description", "Choir — an overlay for Discord"},
        {"disable_environment", {{"DISABLE_CHOIR_OVERLAY", "1"}}},
    };
    return j.dump(2) + "\n";
}

// Kept in sync by hand with packaging/choir-run.in (same reason as the manifest: that
// template's baked path comes from the meson prefix, which an AppImage doesn't have).
std::string gl_wrapper_script(const std::string& gl_lib) {
    return
        "#!/bin/sh\n"
        "# Inject the Choir GL overlay into an OpenGL game:\n"
        "#   choir-run <game…>            # direct\n"
        "#   choir-run %command%          # Steam launch option\n"
        "# Generated by the Choir host for this AppImage install; regenerated whenever the\n"
        "# payload changes. Override the lib path with CHOIR_GL_LIB if needed.\n"
        "default_lib=" + shell_quote(gl_lib) + "\n"
        "lib=\"${CHOIR_GL_LIB:-$default_lib}\"\n"
        "if [ -e \"$lib\" ]; then\n"
        "  # PREPEND (not append) to any existing LD_PRELOAD so Choir loads FIRST. If another\n"
        "  # GL overlay is already injected (e.g. MangoHud), the first interposer wins the hook\n"
        "  # and chains down to the rest; appending would put Choir last, where the earlier\n"
        "  # overlay can resolve the real swap directly and bypass us.\n"
        "  export LD_PRELOAD=\"$lib${LD_PRELOAD:+:$LD_PRELOAD}\"\n"
        "else\n"
        "  # Don't preload a missing path: the loader would warn for the game AND every child\n"
        "  # process it spawns. Launch anyway — a broken overlay must never stop you playing.\n"
        "  echo \"choir-run: GL overlay library not found: $lib\" >&2\n"
        "  echo \"           launching without the overlay; set CHOIR_GL_LIB or reinstall Choir.\" >&2\n"
        "fi\n"
        "exec \"$@\"\n";
}

}  // namespace

std::string appimage_dir() {
    return env_or("APPDIR", "");
}

std::string appimage_payload_dir() {
    const std::string dir = appimage_dir();
    if (dir.empty()) return "";
    return dir + "/usr/lib/choir";
}

std::string backend_lib_dir() {
    return env_or("HOME", "") + "/.local/lib/choir";
}

std::string gl_wrapper_path() {
    return env_or("HOME", "") + "/.local/bin/choir-run";
}

bool backends_up_to_date(const std::string& src_dir, const std::string& dst_dir) {
    for (const char* name : {kLayerLib, kGlLib}) {
        std::string src, dst;
        if (!read_file(fs::path(src_dir) / name, src)) return false;
        if (!read_file(fs::path(dst_dir) / name, dst)) return false;
        if (src != dst) return false;
    }
    return true;
}

bool install_backends(const std::string& src_dir) {
    // Read BOTH libraries before writing either: a truncated payload then fails
    // without having installed half of one.
    std::string layer_bytes, gl_bytes;
    if (!read_file(fs::path(src_dir) / kLayerLib, layer_bytes)) return false;
    if (!read_file(fs::path(src_dir) / kGlLib, gl_bytes)) return false;

    const fs::path lib_dir = backend_lib_dir();
    const fs::path layer_lib = lib_dir / kLayerLib;
    const fs::path gl_lib = lib_dir / kGlLib;

    if (!write_atomic(layer_lib, layer_bytes, 0755)) return false;
    if (!write_atomic(gl_lib, gl_bytes, 0755)) return false;
    if (!write_atomic(gl_wrapper_path(), gl_wrapper_script(gl_lib.string()), 0755)) return false;

    // Manifest LAST. It is what makes the Vulkan loader go looking for the library,
    // so it must never exist before the library it names.
    return write_atomic(vulkan_manifest_path(), layer_manifest(layer_lib.string()), 0644);
}

bool uninstall_backends() {
    const fs::path lib_dir = backend_lib_dir();
    bool ok = true;

    // Manifest FIRST — the exact mirror of install. It is the thing that makes the
    // loader dlopen the layer into every application, so it must stop existing before
    // the library it names, not after.
    for (const std::string& path : {vulkan_manifest_path(),
                                    gl_wrapper_path(),
                                    (lib_dir / kLayerLib).string(),
                                    (lib_dir / kGlLib).string()}) {
        std::error_code ec;
        fs::remove(path, ec);  // absent is success; only a real failure sets ec
        if (ec) ok = false;
    }

    // Take the directory too, but only if we emptied it — anything else in there is
    // not ours to delete.
    std::error_code ec;
    fs::remove(lib_dir, ec);  // fails harmlessly when non-empty
    return ok;
}

}  // namespace choir
